[Audio]
Volume=100

[General]
FooterStyle=floating
FullscreenOnStartUp=true
LastPlayedFile=file:///home/caue/Videos/5jul.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playback]
HWDecoding=vaapi
